branches:
  except:
    - /travis/
skip_tags: true

environment:
  matrix:
    - perl: activeperl
    - perl: cygwinperl
    - perl: strawberryperl

#cache:
#  - C:\strawberry

install:
  - if %perl%==strawberryperl ( if not exist "C:\strawberry" cinst strawberryperl )
  - if %perl%==strawberryperl set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - if not %perl%==cygwinperl perl -v
  - if     %perl%==cygwinperl c:\cygwin\bin\sh -c "/usr/bin/perl -v"
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
# IPC::Run is already preinstalled on StrawberryPerl;
# trying to reinstall/upgrade it may lead to a hanging cpanm
# See also https://github.com/toddr/IPC-Run/issues/98
#  - if %perl%==strawberryperl cpanm --quiet IPC::Run

build_script:
  - set HARNESS_OPTIONS=c:j4
  - if     %perl%==cygwinperl       c:\cygwin\bin\sh -c "PATH=/usr/bin:/bin; perl Build.PL && perl Build && perl Build test"
  - if not %perl%==cygwinperl     ( perl Build.PL && perl Build && perl Build test )
  - if     %perl%==strawberryperl ( perl Build install && perl Build test_installed && perl Build dist_install_and_test )
