branches:
  except:
    - /travis/
skip_tags: true

cache:
  - C:\strawberry

install:
  - if not exist "C:\strawberry" cinst strawberryperl
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
# XXX --installdeps should work
  - cpanm --quiet IPC::Run
#  - cpanm --installdeps .

build_script:
  - perl Build.PL
  - perl Build
  - perl Build test
  - perl Build install
  - perl Build test_installed
