name: CI

on:
  push:
    branches-ignore:
      - '*travis*'
      - '*appveyor*'
      - '*doozer*'

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
## XXX windows not yet working --- TODO
#       os: [ubuntu-latest, windows-latest, macos-latest]
       os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Build and test
      run: |
        perl Build.PL
        ./Build
        ./Build test
      if: "!startsWith(matrix.os,'windows-')"
    - name: Build and test on Windows
      run: |
        c:\strawberry\perl\bin\perl Build.PL
        c:\strawberry\perl\bin\perl Build
        c:\strawberry\perl\bin\perl Build test
      if: "startsWith(matrix.os, 'windows-')"

  coverage:
    name: Test coverage
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: install Devel::Cover::Report::Coveralls
      run: |
        sudo apt-get update -qq
        sudo apt-get install -q --no-install-recommends \
            cpanminus \
            libdevel-cover-perl \
            libcapture-tiny-perl libipc-run-perl libdevel-hide-perl
        sudo cpanm --quiet --notest Devel::Cover::Report::Coveralls
    - name: Build and test with coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOIT_TEST_WITH_SUDO: 1
      run: |
        perl Build.PL
        ./Build
        cover -test -report coveralls
