name: CI

on:
  push:
    branches-ignore:
      - '*travis*'
      - '*appveyor*'
      - '*doozer*'

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
## XXX windows not yet working --- TODO
#       os: [ubuntu-latest, windows-latest, macos-latest]
       os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Build and test
      run: |
        perl Build.PL
        ./Build
        ./Build test
      if: "!startsWith(matrix.os,'windows-')"
    - name: Build and test on Windows
      run: |
        c:\strawberry\perl\bin\perl Build.PL
        c:\strawberry\perl\bin\perl Build
        c:\strawberry\perl\bin\perl Build test
      if: "startsWith(matrix.os, 'windows-')"
